# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  pod 'OrbaOneSdk', :git => 'https://github.com/luechenchris/orbaone-ios-sdk.git'
end
